[build-system]
requires = ["setuptools>=68","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "odin-sdk"
version = "0.1.0"
description = "ODIN Python SDK (OPE sign/send/verify, receipts, exports)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["httpx>=0.27.0","cryptography>=43.0.1"]

[project.scripts]
odin = "odin_sdk.cli:main"
odinpy = "odin_sdk.cli:main"
odin-sdk = "odin_sdk.cli:main"
