coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: 70%
        threshold: 5%
comment:
  layout: "diff"
  require_changes: true
  behavior: default
  hide_project_coverage: false
ignore:
  - "tests/*"
  - "scripts/*"
  - "deploy/*"
