apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odin-gateway.fullname" . }}
  labels:
    {{- include "odin-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "odin-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "odin-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ODIN_GATEWAY_PRIVATE_KEY_B64
              valueFrom:
                secretKeyRef:
                  name: {{ include "odin-gateway.fullname" . }}-secrets
                  key: gateway-seed
            - name: ODIN_GATEWAY_KID
              valueFrom:
                secretKeyRef:
                  name: {{ include "odin-gateway.fullname" . }}-secrets
                  key: gateway-kid
          {{- with .Values.env }}
          {{- range $k, $v := . }}
            - name: {{ $k }}
              value: "{{ $v }}"
          {{- end }}
          {{- end }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "odin-gateway.fullname" . }}
      {{- end }}
