name: CI

# Concurrency prevents piling up redundant runs for the same ref (cancels superseded pushes)
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Prefer wheels (no build) for cryptography to reduce flakiness/time
          pip install --only-binary cryptography -r requirements.txt
          pip install -e packages/odin_sdk
      - name: Cache mypy & ruff
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .ruff_cache
          key: mypy-ruff-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('mypy.ini','requirements.txt') }}
          restore-keys: |
            mypy-ruff-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Run tests
        env:
          PYTEST_ADDOPTS: -ra --maxfail=1
        run: pytest -q -W error::DeprecationWarning -W ignore::UserWarning
      - name: Lint (ruff)
        run: ruff check . --output-format=github
      - name: Type check (mypy)
        run: mypy --config-file mypy.ini packages/odin_core packages/odin_sdk --show-error-codes
