name: CI

# Concurrency prevents piling up redundant runs for the same ref (cancels superseded pushes)
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Prefer wheels (no build) for cryptography to reduce flakiness/time
          pip install --only-binary cryptography -r requirements.txt
          pip install -e packages/odin_sdk
      - name: Cache mypy & ruff
        uses: actions/cache@v4
        with:
          path: |
            .mypy_cache
            .ruff_cache
          key: mypy-ruff-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('mypy.ini','requirements.txt') }}
          restore-keys: |
            mypy-ruff-${{ runner.os }}-${{ matrix.python-version }}-
      - name: Run tests
        env:
          PYTEST_ADDOPTS: -ra --maxfail=1
        run: pytest -q --cov=packages/odin_core --cov=services/gateway --cov-report=term-missing:skip-covered --cov-report=xml -W error::DeprecationWarning -W ignore::UserWarning
      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
            name: coverage-${{ matrix.python-version }}
            path: coverage.xml
      - name: Upload raw coverage data
        uses: actions/upload-artifact@v4
        with:
            name: coverage-data-${{ matrix.python-version }}
            path: .coverage*

  coverage-aggregate:
    name: Coverage Aggregate & Upload
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: cov_artifacts
      - name: Combine coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          ls -R cov_artifacts
          find cov_artifacts -name '.coverage*' -exec cp {} . \;
          coverage combine || true
          # If combine failed (e.g., only one file), still ensure XML exists
          coverage xml -o combined-coverage.xml || cp cov_artifacts/**/coverage.xml combined-coverage.xml
          coverage report || true
      - name: Upload combined coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-combined
          path: combined-coverage.xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: combined-coverage.xml
          flags: python
          fail_ci_if_error: false
          verbose: true
      - name: Lint (ruff)
        run: ruff check . --output-format=github
      - name: Type check (mypy)
        run: mypy --config-file mypy.ini packages/odin_core packages/odin_sdk --show-error-codes
