name: Publish Python SDK (PyPI)

on:
  push:
    tags:
      - "sdk-release-v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip build twine
      - name: Build
        working-directory: packages/odin_sdk
        run: python -m build
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        working-directory: packages/odin_sdk
        run: python -m twine upload dist/*
