name: Publish JS SDK (npm)

on:
  push:
    tags:
      - "js-sdk-v*"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/odin_sdk_js
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      # Pre-release (e.g., 0.1.1-beta.0) → dist-tag "next"
      - name: Publish (pre-release)
        if: contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'rc')
        run: npm publish --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Stable releases (no pre-release tag in version) → "latest"
      - name: Publish (stable)
        if: (!contains(github.ref_name, 'beta')) && (!contains(github.ref_name, 'alpha')) && (!contains(github.ref_name, 'rc'))
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
