name: python-tests

# Temporary compatibility workflow to satisfy legacy required status checks like
# "python-tests / tests (3.11)" until branch protection is updated. Real tests run in CI.
# After updating protection rules, delete this file.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Compatibility pass-through
        run: |
          echo "Legacy python-tests placeholder for required status check."
          echo "Python version: ${{ matrix.python-version }}"
          echo "Update branch protection to remove this check; then delete python-tests.yml."