name: python-tests (deprecated)

# Deprecated: unified into CI workflow (.github/workflows/ci.yml). Left as manual noop to avoid
# lingering failing runs caused by earlier misconfiguration. Safe to delete after branch
# protection / required checks updated.
on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: echo "python-tests workflow deprecated; use CI workflow for tests."