name: python-tests

# Temporary compatibility workflow to satisfy legacy required check 'python-tests / tests'.
# Real testing now lives in CI workflow. Remove this after updating branch protection to drop
# the old required check, then delete this file.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Fast pass-through
        run: |
          echo "python-tests workflow retained only for legacy required status. Actual tests run in CI." 
          echo "Remove branch protection requirement then delete .github/workflows/python-tests.yml"